doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        # @see https://symfony.com/bundles/DoctrineMigrationsBundle/current/index.html#manual-tables
        schema_filter: ~^(?!messenger_messages)~
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Log:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Monolog'
                prefix: 'App\Monolog'
                alias: Log
        filters:
          case_deleted_filter:
              class: App\Doctrine\CaseDeletedFilter
              enabled: true
