# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        editor:
            toolbar: editor
            extraPlugins: 'colorbutton'
            colorButton_colors: 'ff0000'
            colorButton_enableMore: false
            colorButton_enableAutomatic: true
#            removePlugins: ['elementspath']

    toolbars:
        configs:
            editor:
                - ['Bold', 'Italic', 'Underline', 'StrikeThrough']
                - ['BulletedList', 'NumberedList']
                - ['Outdent', 'Indent', 'TextColor']
