itkdev_openid_connect:
  cache_options:
    cache_pool: 'cache.app' # Cache item pool for caching discovery document and CLI login tokens
  openid_providers:
    admin:
      options:
        metadata_url: '%env(CONFIGURATION_URL)%'
        client_id: '%env(CLIENT_ID)%'
        client_secret: '%env(CLIENT_SECRET)%'
        redirect_route: 'default'
  cli_login_options:
    cli_redirect: '%env(CLI_REDIRECT)%' # Redirect route for CLI login
