itkdev_openid_connect:
  cache_options:
    cache_pool: 'cache.app' # Cache item pool for caching discovery document and CLI login tokens
  cli_login_options:
    cli_redirect: '%env(CLI_REDIRECT)%' # Redirect route for CLI login
  openid_providers:
    admin:
      options:
        metadata_url: '%env(ADMIN_OIDC_METADATA_URL)%'
        client_id: '%env(ADMIN_OIDC_CLIENT_ID)%'
        client_secret: '%env(ADMIN_OIDC_CLIENT_SECRET)%'
        redirect_route: 'default'

    board-member:
      options:
        metadata_url: '%env(BOARD_MEMBER_OIDC_METADATA_URL)%'
        client_id: '%env(BOARD_MEMBER_OIDC_CLIENT_ID)%'
        client_secret: '%env(BOARD_MEMBER_OIDC_CLIENT_SECRET)%'
        redirect_route: 'default'
