monolog:
    channels:
        - "database"

    handlers:
        database:
            type: service
            id: App\Monolog\DoctrineHandler
            channels: ["database"]
            # log error-level messages and higher
            level: error
