twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: '%site_name%'
    form_themes: ['bootstrap_4_layout.html.twig']
#    form_themes:
#        - 'bootstrap_4_layout.html.twig'
#        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'