twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: '%site_name%'
        format_date: 'd/m/Y'
        format_time: 'H:i'
        format_datetime: 'd/m/Y H:i'
        format_weekday: 'l'
    form_themes: ['bootstrap_4_layout.html.twig', 'form/theme.html.twig']

    date:
      format: 'd/m/Y H:i'
      # By default translate all datetimes to Copenhagen timezone.
      # Exceptions are agenda & agenda items start/end time.
      # @see e.g. templates/agenda/index.html.twig
      # @see https://twig.symfony.com/doc/2.x/filters/date.html#timezone
      timezone: '%view_timezone%'
