vich_uploader:
    db_driver: orm

    mappings:
        mail_templates:
            uri_prefix: /admin/mail-template/template-file
            upload_destination: '%kernel.project_dir%/upload/mail-templates'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
