# app/config/config.yml
twig:
  form_themes:
    - LexikFormFilterBundle:Form:form_div_layout.html.twig

lexik_form_filter:
  listeners:
    doctrine_orm: true
    doctrine_dbal: false
    doctrine_mongodb: false
  where_method: ~  # null | and | or
