# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: '%env(DEFAULT_LOCALE)%'
    site_name: '%env(SITE_NAME)%'
    site_url: '%env(SITE_URL)%'
    upload_document_directory: 'upload/documents'
    view_timezone: '%env(VIEW_TIMEZONE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $leeway: '%env(LEEWAY)%'

            $bbrHelperOptions:
                datafordeler_api_username: '%env(DATAFORDELER_API_USERNAME)%'
                datafordeler_api_password: '%env(DATAFORDELER_API_PASSWORD)%'
                bbr_data_ttl: '%env(BBR_DATA_TTL)%'

            $logEntryHelperOptions:
                log_entry_display:
                    exclude_keys:
                        # List of keys to exclude from display
                        - createdAt
                        - updatedAt
                        - accusedAddress.validatedAt
                        - accusedAddress.bbrData
                        - complainantAddress.validatedAt
                        - complainantAddress.bbrData
                        - leaseAddress.validatedAt
                        - leaseAddress.bbrData
                        - previousCasesAtLease
                        # A key can be a regex (delimited by /, # or ~).
                        - /^(sorting|hasReached)/
                    translation_domains:
                        # Domains to use for translations
                        case:
                            # Sub-domains. All keys from sub-domains will be
                            # combined with parent domain keys.
                            address:
                        address:


            $loginControllerOptions:
                # Must match firewall name in packages/security.yaml
                firewall_name: main
                # End time of “Remember my choice” cookie.
                cookie_end_time: '+1 month'

            $mailTemplateHelperConfig:

            $mailTemplateHelperOptions:
                template_types:
                    inspection_letter:
                        label: Inspection
                        entity_class_names:
                            # TODO: Modify when inspection is reintroduced
                            - App\Entity\ResidentComplaintBoardCase
                            - App\Entity\FenceReviewCase
                            - App\Entity\RentBoardCase
                    decision:
                        label: Decision
                        entity_class_names:
                            - App\Entity\ResidentComplaintBoardCase
                            - App\Entity\FenceReviewCase
                            - App\Entity\RentBoardCase
                    hearing:
                        label: Hearing
                        entity_class_names:
                            - App\Entity\HearingPost
                    agenda_inspection:
                      label: Agenda inspection
                      entity_class_names:
                        - App\Entity\InspectionLetter
                    agenda_broadcast:
                        label: Agenda broadcast
                        entity_class_names:
                          - App\Entity\AgendaBroadcast
                    board_receipt_case:
                        label: Board receipt (case)
                        entity_class_names:
                            - App\Entity\ResidentComplaintBoardCase
                            - App\Entity\FenceReviewCase
                            - App\Entity\RentBoardCase
                    board_receipt_hearing_post:
                        label: Board receipt (hearing post)
                        entity_class_names:
                            - App\Entity\HearingPost
                    hearing_post_form:
                        label: Hearing_post_form
                        entity_class_names:
                            - App\Entity\HearingPost
                    hearing_post_response_template:
                        label: Hearing post response template
                        entity_class_names:
                            - App\Entity\HearingPostResponse

                upload_destination: '%kernel.project_dir%/upload/mail-templates'
                # This value must match vich_uploader.mappings.mail_templates.upload_destination
                template_file_directory: '%kernel.project_dir%/upload/mail-templates'
                libreoffice_http_client_options:
                    base_uri: '%env(LIBREOFFICE_API_BASE_URL)%'
                    verify_peer: false
                    verify_host: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Logging\EntityListener\:
        resource: '../src/Logging/EntityListener/'
        tags: ['doctrine.orm.entity_listener']

    App\Service\DocumentUploader:
        arguments:
            $projectDirectory: '%kernel.project_dir%'
            $uploadDocumentDirectory: '%upload_document_directory%'

    App\Service\DigitalPostHelper:
        arguments:
            $options:
              digital_post_options:
                digital_post_system_id: '%env(DIGITAL_POST_SYSTEM_ID)%'
                digital_post_afsender_system: '%env(DIGITAL_POST_AFSENDER_SYSTEM)%'

                digital_post_materiale_id: '%env(DIGITAL_POST_MATERIALE_ID)%'

                digital_post_forsendelses_type: '%env(DIGITAL_POST_FORSENDELSES_TYPE)%'

                azure_tenant_id: '%env(AZURE_TENANT_ID)%'
                azure_application_id: '%env(AZURE_APPLICATION_ID)%'
                azure_client_secret: '%env(AZURE_CLIENT_SECRET)%'

                azure_key_vault_name: '%env(AZURE_KEY_VAULT_NAME)%'
                azure_key_vault_secret: '%env(AZURE_KEY_VAULT_SECRET)%'
                azure_key_vault_secret_version: '%env(AZURE_KEY_VAULT_SECRET_VERSION)%'

                service_agreement_uuid: '%env(SERVICE_AGREEMENT_UUID)%'
                user_system_uuid: '%env(USER_SYSTEM_UUID)%'
                user_uuid: '%env(USER_UUID)%'

                service_uuid: '%env(SERVICE_UUID)%'
                service_endpoint: '%env(SERVICE_ENDPOINT)%'
                service_contract: '%env(resolve:SERVICE_CONTRACT)%'

              restriction_options:
                  number_of_attachments_allowed: '%env(NUMBER_OF_ATTACHMENTS_ALLOWED)%'
                  total_filesize_allowed: '%env(TOTAL_FILESIZE_ALLOWED)%'

    # Setting level in config/packages/monolog.yaml does not work as expected
    # (cf. https://github.com/symfony/monolog-bundle/issues/322)
    App\Monolog\DoctrineHandler:
        arguments:
            $level: error

    App\Form\DocumentType:
        arguments:
            $maxFileSize: '%env(FILE_MAX_SIZE)%'

    App\Service\CprHelper:
        arguments:
            $options:
                azure_tenant_id: '%env(AZURE_TENANT_ID)%'
                azure_application_id: '%env(AZURE_APPLICATION_ID)%'
                azure_client_secret: '%env(AZURE_CLIENT_SECRET)%'

                azure_key_vault_name: '%env(AZURE_KEY_VAULT_CPR_NAME)%'
                azure_key_vault_secret: '%env(AZURE_KEY_VAULT_CPR_SECRET)%'
                azure_key_vault_secret_version: '%env(AZURE_KEY_VAULT_CPR_SECRET_VERSION)%'

                serviceplatformen_cpr_service_agreement_uuid: '%env(SERVICEPLATFORMEN_CPR_SERVICE_AGREEMENT_UUID)%'
                serviceplatformen_cpr_user_system_uuid: '%env(SERVICEPLATFORMEN_CPR_USER_SYSTEM_UUID)%'
                serviceplatformen_cpr_user_uuid: '%env(SERVICEPLATFORMEN_CPR_USER_UUID)%'

                serviceplatformen_cpr_service_uuid: '%env(SERVICEPLATFORMEN_CPR_SERVICE_UUID)%'
                serviceplatformen_cpr_service_endpoint: '%env(SERVICEPLATFORMEN_CPR_SERVICE_ENDPOINT)%'
                serviceplatformen_cpr_service_contract: '%env(resolve:SERVICEPLATFORMEN_CPR_SERVICE_CONTRACT)%'

    App\Service\CvrHelper:
        arguments:
            $options:
              azure_tenant_id: '%env(AZURE_TENANT_ID)%'
              azure_application_id: '%env(AZURE_APPLICATION_ID)%'
              azure_client_secret: '%env(AZURE_CLIENT_SECRET)%'

              azure_key_vault_name: '%env(AZURE_KEY_VAULT_DATAFORDELER_NAME)%'
              azure_key_vault_datafordeler_secret: '%env(AZURE_KEY_VAULT_DATAFORDELER_SECRET)%'
              azure_key_vault_datafordeler_secret_version: '%env(AZURE_KEY_VAULT_DATAFORDELER_SECRET_VERSION)%'

              datafordeler_cvr_lookup_base_url: '%env(DATAFORDELER_CVR_LOOKUP_BASE_URL)%'

    App\Service\MailTemplate\ComplexMacroHelper:
        arguments:
            $options:
                formatting:
                    hyperlink:
                        style_name: Hyperlink
                        styles:
                            # See https://phpword.readthedocs.io/en/latest/styles.html#font for styles options.
                            color: 0563C1
                            underline: !php/const \PhpOffice\PhpWord\Style\Font::UNDERLINE_SINGLE
                hearing_post_form_url: '%env(HEARING_POST_FORM_URL)%'
                hearing_post_form_link_text: '%env(HEARING_POST_FORM_LINK_TEXT)%'

    App\Controller\ApiController:
        arguments:
            $options:
                tvist1_api_token: '%env(TVIST1_API_TOKEN)%'

    App\MessageHandler\WebformSubmissionMessageHandler:
        arguments:
            $selvbetjeningUserApiToken: '%env(SELVBETJENING_USER_API_TOKEN)%'

    App\Service\OS2Forms\SubmissionNormalizers\CaseSubmissionNormalizer:
        arguments:
            $selvbetjeningUserApiToken: '%env(SELVBETJENING_USER_API_TOKEN)%'

    App\Service\OS2Forms\SubmissionNormalizers\ResidentAndRentBoardSubmissionNormalizer:
        arguments:
            $selvbetjeningUserApiToken: '%env(SELVBETJENING_USER_API_TOKEN)%'

    App\Service\OS2Forms\SubmissionNormalizers\RentBoardSubmissionNormalizer:
        arguments:
            $selvbetjeningUserApiToken: '%env(SELVBETJENING_USER_API_TOKEN)%'

    App\Service\OS2Forms\SubmissionNormalizers\FenceBoardSubmissionNormalizer:
        arguments:
            $selvbetjeningUserApiToken: '%env(SELVBETJENING_USER_API_TOKEN)%'

    App\Service\OS2Forms\SubmissionNormalizers\HearingResponseSubmissionNormalizer:
        arguments:
            $selvbetjeningUserApiToken: '%env(SELVBETJENING_USER_API_TOKEN)%'

    App\Controller\CaseEventController:
        arguments:
            $options:
              view_timezone: '%view_timezone%'
